http:
    port: 8080
    mode: "debug"
    read-timeout: "60s"
    write-timeout: "60s"
log:
    level: debug
    console: true
    file: ./logs/poop-server.log
    keep: 30
db:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "root"
    database: "poop"
    timeout: "10s"
    max-open-conns: 10
    max-idle-conns: 3
chains:
    bscmain:
        chain-name: "bscmain"
        chain-id: 56
        interval: "10s"
        start-block: 29728954
        delay-block: 1
        max-block: 100
        urls:
            - "https://bsc.getblock.io/371e44be-23e7-475f-9773-04099202349e/mainnet/" 
        abi: 
            Poop: "./config/abi/Poop.json"
        contracts:
            - "0x00000065cBADeAD116136940b302F938284f2BDc"
        addresses: 
            Poop: "0x00000065cBADeAD116136940b302F938284f2BDc"
            PoopRouter: "0xe455b5602245aA22cb6fedE4f7f32C5E29727650"
            WBNBRouter: "0x632c8F7552a1413163026F81F072f8267C3B0dE7"
