http:
    port: 8080
    mode: "debug"
    read-timeout: "60s"
    write-timeout: "60s"
log:
    level: info
    console: true
    file: ./logs/poop-server.log
    keep: 30
db:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "root"
    database: "poop"
    timeout: "10s"
    max-open-conns: 10
    max-idle-conns: 3


